---
- name: Create local user
  hosts: all
  become: yes
  vars:
    - user: {{ user }}
  remote_user: root
  tasks:
    - name: Add my user
      ansible.builtin.user:
        name: '{{ user }}'
        shell: /bin/zsh
        groups: wheel
        expires: -1
    - name: Put authorized_keys
      template:
        src: authorized_keys.j2
        dest:  /home/{{ user }}/.ssh/authorized_keys
        owner: {{ user }}
        group: {{ user }}
        mode: '0600'